// src/components/GameRules.tsx

import React from 'react';
import {
  Modal,
  View,
  Text,
  TouchableOpacity,
  ScrollView,
  StyleSheet,
  Linking,
} from 'react-native';
import {
  X,
  Gift,
  CloudRain,
  Dice5,
  Menu,
  ChevronRight,
} from 'lucide-react-native';

interface GameRulesProps {
  visible: boolean;
  onClose: () => void;
}

const GameRules: React.FC<GameRulesProps> = ({ visible, onClose }) => {
  return (
    <Modal visible={visible} transparent animationType="fade">
      <View style={styles.overlay}>
        <View style={styles.modalContainer}>
          {/* Header */}
          <View style={styles.headerContainer}>
            <Text style={styles.headerTitle}>Game Rules</Text>
            <TouchableOpacity onPress={onClose}>
              <X size={22} color="yellow" />
            </TouchableOpacity>
          </View>

          {/* Scrollable content */}
          <ScrollView showsVerticalScrollIndicator={false}>
            {/* Free Bets */}
            <View style={styles.section}>
              <View style={styles.rowTitle}>
                <Gift size={18} color="yellow" />
                <Text style={styles.sectionTitle}> Free Bets</Text>
              </View>

              <View style={styles.row}>
                <ChevronRight size={16} color="yellow" />
                <Text style={styles.text}>
                  You can check the status of Free Bets from Game Menu {'>'} Free Bets.
                </Text>
              </View>

              <View style={styles.row}>
                <ChevronRight size={16} color="yellow" />
                <Text style={styles.text}>
                  Free Bets are awarded by the operator or by the Rain Feature.
                </Text>
              </View>
            </View>

            {/* Rain Feature */}
            <View style={styles.section}>
              <View style={styles.rowTitle}>
                <CloudRain size={18} color="yellow" />
                <Text style={styles.sectionTitle}> Rain Feature</Text>
              </View>

              <View style={styles.row}>
                <ChevronRight size={16} color="yellow" />
                <Text style={styles.text}>
                  The operator can drop Free Bets into the chat through the Rain feature.
                </Text>
              </View>

              <View style={styles.row}>
                <ChevronRight size={16} color="yellow" />
                <Text style={styles.text}>
                  To claim these Free Bets, just press the “Claim” button when they appear in the chat.
                </Text>
              </View>
            </View>

            {/* Randomisation */}
            <View style={styles.section}>
              <View style={styles.rowTitle}>
                <Dice5 size={18} color="yellow" />
                <Text style={styles.sectionTitle}> Randomisation</Text>
              </View>

              <View style={styles.row}>
                <ChevronRight size={16} color="yellow" />
                <Text style={styles.text}>
                  The multiplier for each round is generated by a “Provably Fair” algorithm and is completely transparent, and 100% fair.{' '}
                  <Text
                    style={styles.link}
                    onPress={() =>
                      Linking.openURL('https://example.com/provably-fair')
                    }>
                    Read more about provably fair system
                  </Text>
                </Text>
              </View>

              <View style={styles.row}>
                <ChevronRight size={16} color="yellow" />
                <Text style={styles.text}>
                  You can check and modify the Provably Fair settings from the Game menu {'>'} Provably Fair settings.
                </Text>
              </View>

              <View style={styles.row}>
                <ChevronRight size={16} color="yellow" />
                <Text style={styles.text}>
                  You can check the fairness of each round by pressing the 🛡 icon, opposite the results in the “My Bets” or inside “Top” tabs.
                </Text>
              </View>
            </View>

            {/* Game Menu */}
            <View style={styles.section}>
              <View style={styles.rowTitle}>
                <Menu size={18} color="yellow" />
                <Text style={styles.sectionTitle}> Game Menu</Text>
              </View>

              <View style={styles.row}>
                <ChevronRight size={16} color="yellow" />
                <Text style={styles.text}>
                  Access the Game Menu by tapping the menu button at the top right corner.
                </Text>
              </View>

              <View style={styles.row}>
                <ChevronRight size={16} color="yellow" />
                <Text style={styles.text}>
                  Toggle “Sound” to turn game sounds on or off.
                </Text>
              </View>

              <View style={styles.row}>
                <ChevronRight size={16} color="yellow" />
                <Text style={styles.text}>
                  Toggle “Music” to turn background music on or off.
                </Text>
              </View>

              <View style={styles.row}>
                <ChevronRight size={16} color="yellow" />
                <Text style={styles.text}>
                  Toggle “Animation” to enable or disable airplane animation.
                </Text>
              </View>

              <View style={styles.row}>
                <ChevronRight size={16} color="yellow" />
                <Text style={styles.text}>
                  Press “Limits” to view minimum and maximum bet limits.
                </Text>
              </View>
            </View>
          </ScrollView>
        </View>
      </View>
    </Modal>
  );
};

export default GameRules;

const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.85)',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  modalContainer: {
    backgroundColor: '#121212',
    borderRadius: 10,
    padding: 20,
    maxHeight: '90%',
  },
  headerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  headerTitle: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  section: {
    marginBottom: 18,
  },
  rowTitle: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  sectionTitle: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  row: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 6,
  },
  text: {
    color: '#ccc',
    fontSize: 14,
    flex: 1,
    lineHeight: 20,
  },
  link: {
    color: 'yellow',
    textDecorationLine: 'underline',
  },
});
